image: node:12.18.4-alpine

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy_staging
  - deploy_production

include:
  - "https://gitlab.com/gitlab-org/gitlab/-/raw/master/lib/gitlab/ci/templates/Security/SAST.gitlab-ci.yml"
  - "https://gitlab.com/gitlab-org/gitlab/-/raw/master/lib/gitlab/ci/templates/Security/Secret-Detection.gitlab-ci.yml"

Test:
  only:
    - develop
    - staging
    - master
  stage: test
  script:
    - export SERVICE_NAME=$DEV_SERVICE_NAME
    - export SERVICE_PORT=$DEV_SERVICE_PORT
    - export ENVIRONMENT=development
    - export DB_HOST=$DEV_DB_HOST
    - export DB_PORT=$DEV_DB_PORT
    - export DB_USER=$DEV_DB_USER
    - export DB_PASS=$DEV_DB_PASS
    - export DB_NAME=$DEV_DB_NAME
    - export SECRET_TOKEN=$DEV_SECRET_TOKEN
    - npm install
    - npm run test

Staging:
  image: ruby:latest
  only:
    - staging
    - master
  stage: deploy_staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$DEV_HEROKU_APP_NAME --api-key=$DEV_HEROKU_API_KEY

Production:
  image: keymetrics/pm2:6
  stage: deploy_production
  only:
    - master
  script:
    - npm install